spring:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate
user:
  datasource:
    url: jdbc:h2:tcp://localhost/~/user
    username: sa
    password:
    driverClassName: org.h2.Driver

customer:
  datasource:
    url: jdbc:h2:tcp://localhost/~/customer
    username: sa
    password:
    driverClassName: org.h2.Driver